name: CD

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      RAILS_MASTER_KEY:
        required: true
      KAMAL_REGISTRY_PASSWORD:
        required: true
      DISCORD_CLIENT_ID:
        required: true
      DISCORD_CLIENT_SECRET:
        required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan 143.198.121.205 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Set up Rails Master Key
        run: echo "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      - name: Deploy with Kamal
        run: bin/kamal deploy
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      
      - name: Prune Unused Images and Containers
        run: bin/kamal prune all
